/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#dadad8',
        'outline': '#80765f',
        'tertiary-container': '#ffc7bf',
        'error-container': '#ffdad6',
        'inverse-primary': '#efc200',
        'tertiary-fixed': '#ffdad5',
        'on-tertiary': '#ffffff',
        'tertiary': '#bb1615',
        'secondary-container': '#47c1ff',
        'surface': '#f9f9f7',
        'surface-bright': '#f9f9f7',
        'on-surface': '#1a1c1b',
        'on-tertiary-fixed': '#410001',
        'on-primary-container': '#6f5900',
        'error': '#ba1a1a',
        'tertiary-fixed-dim': '#ffb4aa',
        'on-secondary-fixed': '#001e2d',
        'secondary-fixed': '#c6e7ff',
        'primary': '#735c00',
        'on-primary-fixed-variant': '#574500',
        'on-background': '#1a1c1b',
        'on-primary-fixed': '#231b00',
        'on-tertiary-container': '#b71212',
        'inverse-surface': '#2f3130',
        'on-secondary-container': '#004d6c',
        'surface-container': '#eeeeec',
        'surface-container-low': '#f4f4f2',
        'secondary-fixed-dim': '#81cfff',
        'surface-variant': '#e2e3e1',
        'on-tertiary-fixed-variant': '#930006',
        'surface-container-high': '#e8e8e6',
        'inverse-on-surface': '#f1f1ef',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#e2e3e1',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffe084',
        'outline-variant': '#d1c6ab',
        'surface-tint': '#735c00',
        'on-surface-variant': '#4e4632',
        'primary-container': '#ffcf00',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#efc200',
        'on-error': '#ffffff',
        'secondary': '#00658d',
        'on-secondary': '#ffffff',
        'background': '#f9f9f7',
        'on-secondary-fixed-variant': '#004c6b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-page': '40px',
        'object-gap': '16px',
        'desk-padding': '32px',
        'gutter': '24px',
      },
      fontFamily: {
        'jakarta': ['Plus Jakarta Sans', 'sans-serif'],
        'mono-brand': ['Space Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-tag': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      boxShadow: {
        'polaroid': '0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06), 0 10px 15px -3px rgba(0,0,0,0.1)',
        'extruded': 'inset 1px 1px 0px rgba(255,255,255,0.5), inset -1px -1px 0px rgba(0,0,0,0.1), 0 4px 6px rgba(0,0,0,0.1)',
        'inset-desk': 'inset 0 2px 4px rgba(0,0,0,0.05)',
        'nav': '0 -4px 10px rgba(0,0,0,0.08)',
      },
      animation: {
        'spin-slow': 'spin 2s linear infinite',
      },
    },
  },
  plugins: [],
};
